### ISSUE TITLE
imu coordinate frame

### ISSUE THREAD

**Issue by Lishen1** [i2Nav-WHU/awesome-gins-datasets#10]
in readme written that imu in NED coordinate frame (z axis towards down) but in imu data file sign of z axis acceleration is negative (while expected positive )

**Comment by thlsealight** [comment]
The IMU used is in the front-right-down (FRD) frame, while is a local frame. In contrast, the NED frame is a global frame. Besides,  please note that the sign of the z-axis acceleration should be negative rather than positive.
