### ISSUE TITLE
Question about IMU data format

### ISSUE THREAD

**Issue by lixiangpengcs** [i2Nav-WHU/awesome-gins-datasets#6]
I am new to this research area. I am curious about the IMU data is represented with angle increment and velocity increment. And the frequency is 200Hz. How to obtain the exact acceleration values and gyro values? Should I obtain them by "increment value *200"?

**Comment by thlsealight** [comment]
You can obtain the average angular velocity and acceleration within the interval by multiply the increment and the time interval.
