### ISSUE TITLE
GNSS数据中的位置标准差数据是如何获取的？

### ISSUE THREAD

**Issue by Dennissy23** [i2Nav-WHU/awesome-gins-datasets#7]
请问GNSS数据中的位置标准差数据是如何获取的，我的RTK设备好像不会输出这个数据

**Comment by thlsealight** [comment]
本数据集的RTK为后处理算法的解算结果，对应的标准差数据由算法输出。对于一般的GNSS接收机，NMEA协议的GPGST消息包含定位的标准差数据。
